[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [
    { access = "read", path = "./out" },
    { access = "write", path = "./reports" }
]
solc = "0.8.25"
optimizer = true
ffi = true

remappings = [
    "@openzeppelin/contracts-upgradeable/=lib/spark-alm-controller/lib/sdai/lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/contracts/=lib/metamorpho/lib/openzeppelin-contracts/contracts/",
    "aave-v3-core/=lib/sparklend-kill-switch/lib/aave-v3-core/",
    "aave-v3-periphery/=lib/aave-v3-periphery/contracts/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "dss-allocator/=lib/dss-allocator/",
    "dss-exec-lib/=lib/spells-mainnet/lib/dss-exec-lib/src/",
    "dss-interfaces/=lib/dss-test/lib/dss-interfaces/src/",
    "dss-test/=lib/dss-test/src/",
    "erc20-helpers/=lib/erc20-helpers/src/",
    "erc4626-tests/=lib/metamorpho/lib/erc4626-tests/",
    "forge-std/=lib/forge-std/src/",
    "metamorpho/=lib/metamorpho/src/",
    "morpho-blue/=lib/metamorpho/lib/morpho-blue/",
    "murky/=lib/metamorpho/lib/universal-rewards-distributor/lib/murky/src/",
    "openzeppelin-contracts-upgradeable/=lib/spark-alm-controller/lib/sdai/lib/openzeppelin-contracts-upgradeable/",
    "openzeppelin-contracts/=lib/spark-alm-controller/lib/openzeppelin-contracts/",
    "openzeppelin-foundry-upgrades/=lib/spark-alm-controller/lib/sdai/lib/openzeppelin-foundry-upgrades/src/",
    "openzeppelin/=lib/metamorpho/lib/universal-rewards-distributor/lib/openzeppelin-contracts/contracts/",
    "sdai/=lib/spark-alm-controller/lib/sdai/",
    "solidity-stringutils/=lib/spark-alm-controller/lib/sdai/lib/openzeppelin-foundry-upgrades/lib/solidity-stringutils/",
    "spark-address-registry/=lib/spark-address-registry/src/",
    "spark-alm-controller/=lib/spark-alm-controller/",
    "spark-gov-relay/=lib/spark-gov-relay/",
    "spark-psm/=lib/spark-alm-controller/lib/spark-psm/",
    "sparklend-address-registry/=lib/spark-alm-controller/lib/spark-psm/lib/xchain-ssr-oracle/lib/sparklend-address-registry/",
    "sparklend-cap-automator/=lib/sparklend-cap-automator/src/",
    "sparklend-freezer/=lib/sparklend-freezer/src/",
    "sparklend-kill-switch/=lib/sparklend-kill-switch/src/",
    "sparklend-v1-core/=lib/sparklend-v1-core/",
    "spells-mainnet/=lib/spells-mainnet/",
    "token-tests/=lib/spark-alm-controller/lib/sdai/lib/token-tests/src/",
    "universal-rewards-distributor/=lib/metamorpho/lib/universal-rewards-distributor/src/",
    "usds/=lib/spark-alm-controller/lib/usds/",
    "xchain-helpers/=lib/xchain-helpers/src/",
    "xchain-ssr-oracle/=lib/spark-alm-controller/lib/spark-psm/lib/xchain-ssr-oracle/"
]
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
