[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [
    { access = "read", path = "./out" },
    { access = "write", path = "./reports" }
]
solc = "0.8.25"
optimizer = true
ffi = true

remappings = [
    "openzeppelin-contracts/=lib/openzeppelin-contracts/", # Needed for ALM controller compilation
]
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
