name: Run Payload on Tenderly

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
  workflow_dispatch:
    inputs:
      parameter_name:
        description: 'Description of the input parameter'
        required: true
        default: 'Default value'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Run Tenderly Script
      env:
          TENDERLY_ACCESS_KEY: ${{secrets.TENDERLY_ACCESS_KEY}}
          TENDERLY_PROJECT: ${{secrets.TENDERLY_PROJECT}}
          TENDERLY_USER: ${{secrets.TENDERLY_USER}}
      run: |
        npm install
        echo RPC URL = $(node tenderly.js)

